---
tmp_dir: "/ibex/tmp/naras0c"
output_dir: "/ibex/user/naras0c/ww_public_datasets/output/PRJEB13233_wekaio"
data_table: "/ibex/user/naras0c/ww_public_datasets/metadata/PRJEB13233_mg_mt_data.tsv"
input_dir:
  download: "/ibex/user/naras0c/ww_public_datasets/input"
  mt_assembly_input: "/ibex/user/naras0c/ww_public_datasets/PRJEB13233/preprocessing/metatranscriptomics"
  mg_assembly_input: "/ibex/user/naras0c/ww_public_datasets/PRJEB13233/preprocessing/metagenomics"
  coassembly_input: "/ibex/user/naras0c/ww_public_datasets/PRJEB13233/assembly/metatranscriptomics"

trimmomatic:
    adapters_path: "/ibex/user/naras0c/ww_public_datasets/adapters/all_illumina_adapters.fa"

sortmerna:
    db_path: "/ibex/user/naras0c/sortmerna"
    filter_length: 20
    human_genome_fasta_path: "/ibex/reference/KSL/Homo_sapiens_assembly38/Homo_sapiens_assembly38.fasta"
    human_mrna_fasta_path: "/ibex/user/naras0c/genomes/human/mrna.fa"

salmon:
    min_assigned_frags: 1
